<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="PC" name="go.mail.ru.tests.SimpleTest" tests="12" failures="0" timestamp="15 Mar 2014 15:38:14 GMT" time="75.738" errors="1">
  <testcase name="testImageOnMainPage" time="13.704" classname="go.mail.ru.tests.SimpleTest"/>
  <testcase name="testSuggests" time="2.923" classname="go.mail.ru.tests.SimpleTest">
    <error type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at go.mail.ru.tests.SimpleTest.testSuggests(SimpleTest.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:722)
]]>
    </error>
  </testcase> <!-- testSuggests -->
  <testcase name="testResult" time="5.279" classname="go.mail.ru.tests.SimpleTest"/>
  <testcase name="testPlaceholderSearchForm" time="1.295" classname="go.mail.ru.tests.SimpleTest"/>
  <testcase name="testResult" time="4.902" classname="go.mail.ru.tests.SimpleTest"/>
  <testcase name="testSuggests" time="4.599" classname="go.mail.ru.tests.SimpleTest"/>
  <testcase name="testPlaceholderSearchForm" time="0.938" classname="go.mail.ru.tests.SimpleTest"/>
  <testcase name="testAdvancedSearch" time="8.232" classname="go.mail.ru.tests.SimpleTest"/>
  <testcase name="testAdvancedSearch" time="11.334" classname="go.mail.ru.tests.SimpleTest"/>
  <testcase name="testTopMenu" time="3.910" classname="go.mail.ru.tests.SimpleTest"/>
  <testcase name="testImageOnMainPage" time="14.398" classname="go.mail.ru.tests.SimpleTest"/>
  <testcase name="testTopMenu" time="4.224" classname="go.mail.ru.tests.SimpleTest"/>
</testsuite> <!-- go.mail.ru.tests.SimpleTest -->
